# Generated by Django 5.2.1 on 2025-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
